version: '3.7'

services:

  selenoid-node-red-node:
    container_name: selenoid-node-red-node
    hostname: selenoid-node-red-node
    image: selenoid-node-red-node
    build:
      context: .
      dockerfile: node-red.Dockerfile
    network_mode: "host"
    env_file: .env
